name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
